global:
  scrape_interval: "1m"
  scrape_timeout: "10s"
  
  external_labels:
    env: localhost

scrape_configs:
  - job_name: "windows-exporter"
    scrape_interval: "1m"
    scrape_timeout: "10s"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - host.docker.internal:9182
        labels:
          env: localhost
          service: "windows-exporter"

